#!/usr/bin/env bash
# =============================================================================
# build_qa_gh200.sh — produce quality-assesment-gh200.sqsh
#
# Pattern mirrors datacur/tools/build_image_gh200_cuda.sh:
#   1. enroot create writable rootfs from the cuda-fix base
#   2. enroot start --rw --root  → run setup_qa_gh200.sh inside
#   3. enroot export to .sqsh
#   4. write the EDF .toml
#
# Idempotent: re-runs reuse the writable container ("$CONTAINER_NAME") if it
# already exists. Pass FORCE_RECREATE=1 to start fresh.
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BASE_SQSH="/capstor/store/cscs/swissai/infra01/MLLM/containers/nemo-curator+26.02-cuda-fix.aarch64.sqsh"
OUT_DIR="/iopsstor/scratch/cscs/$USER/containers"
OUT_SQSH="$OUT_DIR/quality-assesment-gh200.sqsh"
OUT_TOML="$HOME/.edf/quality-assesment-gh200.toml"
CONTAINER_NAME="${CONTAINER_NAME:-qa-gh200-build}"
# Stage scripts on /iopsstor — enroot bind mounts of /users paths intermittently
# fail on this host with "No such file or directory" even when the source exists
# (likely due to the order in which enroot's hooks set up the user-home mount).
STAGING_DIR="$OUT_DIR/qa-build-staging"

echo "=== Prerequisites ==="
command -v enroot >/dev/null || { echo "ERROR: enroot not found"; exit 1; }
[ -f "$BASE_SQSH" ] || { echo "ERROR: base image not found: $BASE_SQSH"; exit 1; }
mkdir -p "$OUT_DIR" "$STAGING_DIR" "$(dirname "$OUT_TOML")"

# Copy scripts into a stable, enroot-friendly location.
cp -f "$SCRIPT_DIR"/setup_qa_gh200.sh \
      "$SCRIPT_DIR"/validate_qa_gh200.sh \
      "$STAGING_DIR/"
chmod +x "$STAGING_DIR"/*.sh

if [ "${FORCE_RECREATE:-0}" = "1" ]; then
    enroot remove -f "$CONTAINER_NAME" 2>/dev/null || true
fi

echo ""
echo "=== Step 1: writable container ($CONTAINER_NAME) ==="
if enroot list 2>/dev/null | grep -qx "$CONTAINER_NAME"; then
    echo "  reusing existing $CONTAINER_NAME"
else
    enroot create --name "$CONTAINER_NAME" "$BASE_SQSH"
fi

echo ""
echo "=== Step 1b: ensure mount-point /qa-tools exists in container ==="
ENROOT_SLURM_HOOK=off enroot start --rw --root "$CONTAINER_NAME" \
    bash -c 'mkdir -p /qa-tools && echo "  /qa-tools ready"'

echo ""
echo "=== Step 2: install deps inside container ==="
ENROOT_SLURM_HOOK=off enroot start --rw --root \
    --mount "$STAGING_DIR:/qa-tools" \
    "$CONTAINER_NAME" \
    bash /qa-tools/setup_qa_gh200.sh

echo ""
echo "=== Step 3: in-container validation probes ==="
ENROOT_SLURM_HOOK=off enroot start --rw --root \
    --mount "$STAGING_DIR:/qa-tools" \
    "$CONTAINER_NAME" \
    bash /qa-tools/validate_qa_gh200.sh

echo ""
echo "=== Step 4: export to sqsh ==="
echo "    target: $OUT_SQSH"
TMP_OUT="${OUT_SQSH}.tmp.$$"
enroot export --output "$TMP_OUT" "$CONTAINER_NAME"
mv -f "$TMP_OUT" "$OUT_SQSH"
ls -lh "$OUT_SQSH"

echo ""
echo "=== Step 5: EDF .toml ==="
cat > "$OUT_TOML" <<TOML
# Auto-generated by build_qa_gh200.sh
# Base: $BASE_SQSH
# Built: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Adds NeMo >= 2.5 (canary-1b-v2 native timestamps + new aligner_utils API),
# Alvorecer721/lhotse fork (fix/duration-batcher-and-shar-reader), audiobox
# metrics, duckdb (exact dedup), data-analysis tools (sklearn/seaborn/polars/
# plotly/jupyterlab), experiment tracking (wandb/tensorboard/mlflow/aim),
# and best-effort vLLM, on top of the cuda-fix base.
# /opt/NeMo is intentionally NOT included anymore — see NFA_API_MIGRATION.md.

image = "$OUT_SQSH"

mounts = [
  "/capstor/store/cscs/swissai/infra01/audio-datasets:/capstor/store/cscs/swissai/infra01/audio-datasets:ro",
  "/iopsstor/scratch/cscs/$USER:/iopsstor/scratch/cscs/$USER",
  "/users/$USER:/users/$USER",
  "/capstor/scratch/cscs/$USER:/capstor/scratch/cscs/$USER",
]

workdir = "/iopsstor/scratch/cscs/$USER"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
# torch 2.9 renamed PYTORCH_CUDA_ALLOC_CONF → PYTORCH_ALLOC_CONF.
PYTORCH_ALLOC_CONF = "expandable_segments:True"
OMP_NUM_THREADS = "1"
MKL_NUM_THREADS = "1"
OPENBLAS_NUM_THREADS = "1"
NUMEXPR_NUM_THREADS = "1"
VECLIB_MAXIMUM_THREADS = "1"
TOML

echo "    written: $OUT_TOML"

echo ""
echo "=== Done ==="
echo "Image: $OUT_SQSH"
echo "EDF:   $OUT_TOML"
echo ""
echo "To clean up the writable build container:"
echo "  enroot remove -f $CONTAINER_NAME"
